// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: payNotice/pay_notice.proto

package payNotice

import (
	fmt "fmt"
	common "github.com/cargod-bj/b2c-proto-common/common"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for PayNotice service

func NewPayNoticeEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for PayNotice service

type PayNoticeService interface {
	Notice(ctx context.Context, in *NoticeDTO, opts ...client.CallOption) (*common.Response, error)
}

type payNoticeService struct {
	c    client.Client
	name string
}

func NewPayNoticeService(name string, c client.Client) PayNoticeService {
	return &payNoticeService{
		c:    c,
		name: name,
	}
}

func (c *payNoticeService) Notice(ctx context.Context, in *NoticeDTO, opts ...client.CallOption) (*common.Response, error) {
	req := c.c.NewRequest(c.name, "PayNotice.Notice", in)
	out := new(common.Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for PayNotice service

type PayNoticeHandler interface {
	Notice(context.Context, *NoticeDTO, *common.Response) error
}

func RegisterPayNoticeHandler(s server.Server, hdlr PayNoticeHandler, opts ...server.HandlerOption) error {
	type payNotice interface {
		Notice(ctx context.Context, in *NoticeDTO, out *common.Response) error
	}
	type PayNotice struct {
		payNotice
	}
	h := &payNoticeHandler{hdlr}
	return s.Handle(s.NewHandler(&PayNotice{h}, opts...))
}

type payNoticeHandler struct {
	PayNoticeHandler
}

func (h *payNoticeHandler) Notice(ctx context.Context, in *NoticeDTO, out *common.Response) error {
	return h.PayNoticeHandler.Notice(ctx, in, out)
}
