// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: testDrive/testDrive.proto

package testDrive

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/any"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for TestDrive service

func NewTestDriveEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for TestDrive service

type TestDriveService interface {
	//新增试驾，返回data.nil
	Add(ctx context.Context, in *TestDriveDTO, opts ...client.CallOption) (*Response, error)
	//根据id删除试驾,这里是假删除设置status为1，返回data.nil
	Delete(ctx context.Context, in *DeleteId, opts ...client.CallOption) (*Response, error)
	//更新试驾信息，返回data.nil
	Update(ctx context.Context, in *TestDriveDTO, opts ...client.CallOption) (*Response, error)
	//获取试驾信息列表，返回列表数据
	GetList(ctx context.Context, in *TestDriveCondition, opts ...client.CallOption) (*Response, error)
}

type testDriveService struct {
	c    client.Client
	name string
}

func NewTestDriveService(name string, c client.Client) TestDriveService {
	return &testDriveService{
		c:    c,
		name: name,
	}
}

func (c *testDriveService) Add(ctx context.Context, in *TestDriveDTO, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "TestDrive.Add", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *testDriveService) Delete(ctx context.Context, in *DeleteId, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "TestDrive.Delete", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *testDriveService) Update(ctx context.Context, in *TestDriveDTO, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "TestDrive.Update", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *testDriveService) GetList(ctx context.Context, in *TestDriveCondition, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "TestDrive.GetList", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for TestDrive service

type TestDriveHandler interface {
	//新增试驾，返回data.nil
	Add(context.Context, *TestDriveDTO, *Response) error
	//根据id删除试驾,这里是假删除设置status为1，返回data.nil
	Delete(context.Context, *DeleteId, *Response) error
	//更新试驾信息，返回data.nil
	Update(context.Context, *TestDriveDTO, *Response) error
	//获取试驾信息列表，返回列表数据
	GetList(context.Context, *TestDriveCondition, *Response) error
}

func RegisterTestDriveHandler(s server.Server, hdlr TestDriveHandler, opts ...server.HandlerOption) error {
	type testDrive interface {
		Add(ctx context.Context, in *TestDriveDTO, out *Response) error
		Delete(ctx context.Context, in *DeleteId, out *Response) error
		Update(ctx context.Context, in *TestDriveDTO, out *Response) error
		GetList(ctx context.Context, in *TestDriveCondition, out *Response) error
	}
	type TestDrive struct {
		testDrive
	}
	h := &testDriveHandler{hdlr}
	return s.Handle(s.NewHandler(&TestDrive{h}, opts...))
}

type testDriveHandler struct {
	TestDriveHandler
}

func (h *testDriveHandler) Add(ctx context.Context, in *TestDriveDTO, out *Response) error {
	return h.TestDriveHandler.Add(ctx, in, out)
}

func (h *testDriveHandler) Delete(ctx context.Context, in *DeleteId, out *Response) error {
	return h.TestDriveHandler.Delete(ctx, in, out)
}

func (h *testDriveHandler) Update(ctx context.Context, in *TestDriveDTO, out *Response) error {
	return h.TestDriveHandler.Update(ctx, in, out)
}

func (h *testDriveHandler) GetList(ctx context.Context, in *TestDriveCondition, out *Response) error {
	return h.TestDriveHandler.GetList(ctx, in, out)
}
