// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: orderFee/orderFee.proto

package orderFee

import (
	fmt "fmt"
	common "github.com/cargod-bj/b2c-proto-common/common"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for OrderFee service

func NewOrderFeeEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for OrderFee service

type OrderFeeService interface {
	Add(ctx context.Context, in *OrderFeeDto, opts ...client.CallOption) (*common.Response, error)
	Delete(ctx context.Context, in *OrderFeeDto, opts ...client.CallOption) (*common.Response, error)
	Update(ctx context.Context, in *OrderFeeDto, opts ...client.CallOption) (*common.Response, error)
}

type orderFeeService struct {
	c    client.Client
	name string
}

func NewOrderFeeService(name string, c client.Client) OrderFeeService {
	return &orderFeeService{
		c:    c,
		name: name,
	}
}

func (c *orderFeeService) Add(ctx context.Context, in *OrderFeeDto, opts ...client.CallOption) (*common.Response, error) {
	req := c.c.NewRequest(c.name, "OrderFee.Add", in)
	out := new(common.Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderFeeService) Delete(ctx context.Context, in *OrderFeeDto, opts ...client.CallOption) (*common.Response, error) {
	req := c.c.NewRequest(c.name, "OrderFee.Delete", in)
	out := new(common.Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderFeeService) Update(ctx context.Context, in *OrderFeeDto, opts ...client.CallOption) (*common.Response, error) {
	req := c.c.NewRequest(c.name, "OrderFee.Update", in)
	out := new(common.Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for OrderFee service

type OrderFeeHandler interface {
	Add(context.Context, *OrderFeeDto, *common.Response) error
	Delete(context.Context, *OrderFeeDto, *common.Response) error
	Update(context.Context, *OrderFeeDto, *common.Response) error
}

func RegisterOrderFeeHandler(s server.Server, hdlr OrderFeeHandler, opts ...server.HandlerOption) error {
	type orderFee interface {
		Add(ctx context.Context, in *OrderFeeDto, out *common.Response) error
		Delete(ctx context.Context, in *OrderFeeDto, out *common.Response) error
		Update(ctx context.Context, in *OrderFeeDto, out *common.Response) error
	}
	type OrderFee struct {
		orderFee
	}
	h := &orderFeeHandler{hdlr}
	return s.Handle(s.NewHandler(&OrderFee{h}, opts...))
}

type orderFeeHandler struct {
	OrderFeeHandler
}

func (h *orderFeeHandler) Add(ctx context.Context, in *OrderFeeDto, out *common.Response) error {
	return h.OrderFeeHandler.Add(ctx, in, out)
}

func (h *orderFeeHandler) Delete(ctx context.Context, in *OrderFeeDto, out *common.Response) error {
	return h.OrderFeeHandler.Delete(ctx, in, out)
}

func (h *orderFeeHandler) Update(ctx context.Context, in *OrderFeeDto, out *common.Response) error {
	return h.OrderFeeHandler.Update(ctx, in, out)
}
