// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: consultationList/consultationList.proto

package consultationList

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/protobuf/types/known/anypb"
	math "math"
)

import (
	context "context"
	api "github.com/micro/micro/v3/service/api"
	client "github.com/micro/micro/v3/service/client"
	server "github.com/micro/micro/v3/service/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for ConsultationList service

func NewConsultationListEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for ConsultationList service

type ConsultationListService interface {
	Add(ctx context.Context, in *ConsultationListDTO, opts ...client.CallOption) (*Response, error)
	Delete(ctx context.Context, in *DeleteId, opts ...client.CallOption) (*Response, error)
	Update(ctx context.Context, in *ConsultationListDTO, opts ...client.CallOption) (*Response, error)
}

type consultationListService struct {
	c    client.Client
	name string
}

func NewConsultationListService(name string, c client.Client) ConsultationListService {
	return &consultationListService{
		c:    c,
		name: name,
	}
}

func (c *consultationListService) Add(ctx context.Context, in *ConsultationListDTO, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "ConsultationList.Add", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *consultationListService) Delete(ctx context.Context, in *DeleteId, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "ConsultationList.Delete", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *consultationListService) Update(ctx context.Context, in *ConsultationListDTO, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "ConsultationList.Update", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ConsultationList service

type ConsultationListHandler interface {
	Add(context.Context, *ConsultationListDTO, *Response) error
	Delete(context.Context, *DeleteId, *Response) error
	Update(context.Context, *ConsultationListDTO, *Response) error
}

func RegisterConsultationListHandler(s server.Server, hdlr ConsultationListHandler, opts ...server.HandlerOption) error {
	type consultationList interface {
		Add(ctx context.Context, in *ConsultationListDTO, out *Response) error
		Delete(ctx context.Context, in *DeleteId, out *Response) error
		Update(ctx context.Context, in *ConsultationListDTO, out *Response) error
	}
	type ConsultationList struct {
		consultationList
	}
	h := &consultationListHandler{hdlr}
	return s.Handle(s.NewHandler(&ConsultationList{h}, opts...))
}

type consultationListHandler struct {
	ConsultationListHandler
}

func (h *consultationListHandler) Add(ctx context.Context, in *ConsultationListDTO, out *Response) error {
	return h.ConsultationListHandler.Add(ctx, in, out)
}

func (h *consultationListHandler) Delete(ctx context.Context, in *DeleteId, out *Response) error {
	return h.ConsultationListHandler.Delete(ctx, in, out)
}

func (h *consultationListHandler) Update(ctx context.Context, in *ConsultationListDTO, out *Response) error {
	return h.ConsultationListHandler.Update(ctx, in, out)
}
