// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: contactRecord/contactRecord.proto

package contactRecord

import (
	fmt "fmt"
	common "github.com/cargod-bj/b2c-proto-common/common"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for ContactRecord service

func NewContactRecordEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for ContactRecord service

type ContactRecordService interface {
	//新增沟通记录，返回data.nil
	Add(ctx context.Context, in *ContactRecordDTO, opts ...client.CallOption) (*common.Response, error)
	//获取试驾信息列表，返回列表数据
	GetList(ctx context.Context, in *ContactRecordCondition, opts ...client.CallOption) (*common.Response, error)
}

type contactRecordService struct {
	c    client.Client
	name string
}

func NewContactRecordService(name string, c client.Client) ContactRecordService {
	return &contactRecordService{
		c:    c,
		name: name,
	}
}

func (c *contactRecordService) Add(ctx context.Context, in *ContactRecordDTO, opts ...client.CallOption) (*common.Response, error) {
	req := c.c.NewRequest(c.name, "ContactRecord.Add", in)
	out := new(common.Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contactRecordService) GetList(ctx context.Context, in *ContactRecordCondition, opts ...client.CallOption) (*common.Response, error) {
	req := c.c.NewRequest(c.name, "ContactRecord.GetList", in)
	out := new(common.Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ContactRecord service

type ContactRecordHandler interface {
	//新增沟通记录，返回data.nil
	Add(context.Context, *ContactRecordDTO, *common.Response) error
	//获取试驾信息列表，返回列表数据
	GetList(context.Context, *ContactRecordCondition, *common.Response) error
}

func RegisterContactRecordHandler(s server.Server, hdlr ContactRecordHandler, opts ...server.HandlerOption) error {
	type contactRecord interface {
		Add(ctx context.Context, in *ContactRecordDTO, out *common.Response) error
		GetList(ctx context.Context, in *ContactRecordCondition, out *common.Response) error
	}
	type ContactRecord struct {
		contactRecord
	}
	h := &contactRecordHandler{hdlr}
	return s.Handle(s.NewHandler(&ContactRecord{h}, opts...))
}

type contactRecordHandler struct {
	ContactRecordHandler
}

func (h *contactRecordHandler) Add(ctx context.Context, in *ContactRecordDTO, out *common.Response) error {
	return h.ContactRecordHandler.Add(ctx, in, out)
}

func (h *contactRecordHandler) GetList(ctx context.Context, in *ContactRecordCondition, out *common.Response) error {
	return h.ContactRecordHandler.GetList(ctx, in, out)
}
