// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: payCallback/pay_callback.proto

package payCallback

import (
	fmt "fmt"
	common "github.com/cargod-bj/b2c-proto-common/common"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for PayCallback service

func NewPayCallbackEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for PayCallback service

type PayCallbackService interface {
	Notice(ctx context.Context, in *NoticeDTO, opts ...client.CallOption) (*common.Response, error)
}

type payCallbackService struct {
	c    client.Client
	name string
}

func NewPayCallbackService(name string, c client.Client) PayCallbackService {
	return &payCallbackService{
		c:    c,
		name: name,
	}
}

func (c *payCallbackService) Notice(ctx context.Context, in *NoticeDTO, opts ...client.CallOption) (*common.Response, error) {
	req := c.c.NewRequest(c.name, "PayCallback.Notice", in)
	out := new(common.Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for PayCallback service

type PayCallbackHandler interface {
	Notice(context.Context, *NoticeDTO, *common.Response) error
}

func RegisterPayCallbackHandler(s server.Server, hdlr PayCallbackHandler, opts ...server.HandlerOption) error {
	type payCallback interface {
		Notice(ctx context.Context, in *NoticeDTO, out *common.Response) error
	}
	type PayCallback struct {
		payCallback
	}
	h := &payCallbackHandler{hdlr}
	return s.Handle(s.NewHandler(&PayCallback{h}, opts...))
}

type payCallbackHandler struct {
	PayCallbackHandler
}

func (h *payCallbackHandler) Notice(ctx context.Context, in *NoticeDTO, out *common.Response) error {
	return h.PayCallbackHandler.Notice(ctx, in, out)
}
